id: AE256C966
title: f0829
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 16:09:25.908274
  last_modified_at: 2022-05-27 16:09:25.908277
