id: AE256C966
title: fF0A7
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 16:09:26.564952
  last_modified_at: 2022-05-27 16:09:26.564955
