id: AE256C966
title: f42C4
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 16:09:26.066548
  last_modified_at: 2022-05-27 16:09:26.066551
