id: AE256C966
title: f055A
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 16:09:25.894091
  last_modified_at: 2022-05-27 16:09:25.894094
