id: AE256C966
title: fD008
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 16:09:26.462078
  last_modified_at: 2022-05-27 16:09:26.462083
