id: AE256C966
title: fE40E
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 16:09:26.519299
  last_modified_at: 2022-05-27 16:09:26.519302
